-- qflow2.draft_audit_node definition

CREATE TABLE `draft_audit_node` (
  `audit_node_id` int NOT NULL AUTO_INCREMENT COMMENT '审核节点ID',
  `form_id` int NOT NULL COMMENT '表单ID',
  `type` int DEFAULT NULL COMMENT '节点类型：0，实节点；1，分支节点；2，自动判定节点；3, qrobot节点',
  `deal_type` int DEFAULT NULL COMMENT '一般处理节点的具体节点类型，0－3分别代表审批节点／填写节点／抄送节点/申请人节点；qrobot节点中，0: 新增数据',
  `prev_id` int DEFAULT NULL COMMENT '前一节点id，若为开始节点，该值为null',
  `next_id` int DEFAULT NULL COMMENT '后一节点id，若为结束节点，该值为null',
  `audit_node_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '审核节点名称',
  `audit_feedback` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启审批反馈',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_upd_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `revert` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否允许回退',
  `transfer` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否移交给其他成员',
  `related_form_id` int DEFAULT NULL COMMENT 'qrobot新增/修改数据节点关联的应用formid',
  `being_old` tinyint(1) NOT NULL DEFAULT '0',
  `being_branch_end` tinyint(1) NOT NULL DEFAULT '0',
  `being_que_check` tinyint(1) DEFAULT '0' COMMENT '节点数据校验是否开启，true：通过校验的数据才可以提交',
  `uid` int DEFAULT NULL,
  `timeout_remind` tinyint(1) NOT NULL DEFAULT '0' COMMENT '节点超时提醒',
  `timeout_warning` tinyint(1) NOT NULL DEFAULT '0' COMMENT '超时预警开关',
  `timeout_type` int DEFAULT NULL COMMENT '超时设置时间类型，1 天 2 小时 3 分',
  `timeout_value` int DEFAULT NULL COMMENT '超时设置具体时间',
  `timeout_compare_type` int DEFAULT NULL COMMENT '超时为根据表单内字段时，对比类型，1: 当天，2： 之前，3：之后',
  `timeout_que_id` int DEFAULT NULL COMMENT '超时为根据表单内字段时，字段的queId',
  `timeout_time` datetime DEFAULT NULL COMMENT '超时为根据表单内字段时，具体的发送时间',
  `timeout_warning_type` int DEFAULT NULL COMMENT '超时预警设置时间类型',
  `timeout_warning_value` int DEFAULT NULL COMMENT '超时预警设置具体时间',
  `timeout_warning_set_current_auditor` tinyint(1) DEFAULT '1' COMMENT '是否设置当前节点负责人为超时预警通知人',
  `judge_formula` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `timeout_set_current_auditor` tinyint(1) DEFAULT '1' COMMENT '是否设置当前节点负责人为超时通知人',
  `approve_btn_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '通过按钮',
  `reject_btn_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '拒绝按钮',
  `revert_btn_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '回退按钮',
  `submit_btn_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '提交按钮',
  `approve_type` int DEFAULT '1' COMMENT '审批节点类型，1：或签，2：会签',
  `mail_notice` tinyint(1) NOT NULL DEFAULT '0',
  `wx_notice` tinyint(1) NOT NULL DEFAULT '0',
  `qrobot_que_filter_formula` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'qrobot更新数据条件',
  `qrobot_que_relation_formula` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'qrobot更新数据对应关系',
  `audit_record_visible` tinyint(1) DEFAULT '1',
  `asos_chart_visible` tinyint(1) DEFAULT '1' COMMENT '节点是否可见关联报表，申请人默认为false，其他处理节点默认为true',
  `auto_deal_status` tinyint(1) DEFAULT '0' COMMENT '超时自动处理状态',
  `auto_deal_compare_type` int DEFAULT NULL COMMENT '1: 当天，3：之后',
  `auto_deal_compare_unit` int DEFAULT NULL COMMENT '单位，1: 天，2:时，3: 分',
  `auto_deal_compare_value` int DEFAULT NULL COMMENT '相差的天数',
  `submit_recalc_status` tinyint NOT NULL DEFAULT '0' COMMENT '提交时重新计算是否开启',
  `transfer_btn_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '转交按钮',
  `comment_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否开启留言',
  `batch_operate_status` tinyint(1) DEFAULT '0',
  `qrobot_update_miss_add_status` tinyint(1) NOT NULL DEFAULT '0',
  `qrobot_miss_add_relation_formula` text CHARACTER SET utf8 COLLATE utf8_general_ci,
  `e_sign_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启电子签章',
  `limit_type` int DEFAULT '1' COMMENT '1: 可以查看全部关联报表，2：限制关联报表可查看范围',
  `reject_btn_status` tinyint(1) DEFAULT '1' COMMENT '拒绝按钮是否显示，0：不显示，1：显示',
  `default_print_tpl_status` tinyint(1) DEFAULT '1' COMMENT '默认打印模板是否显示，0：不显示，1：显示',
  `transfer_scope` int NOT NULL DEFAULT '1' COMMENT '可转交范围，1：工作区所有成员，2：指定成员',
  `revert_scope` int NOT NULL DEFAULT '1' COMMENT '限制回退节点的类型',
  `hand_sign_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启手写签名',
  `online_pay_info_status` tinyint(1) DEFAULT '0' COMMENT '当前节点是否可见支付信息',
  `online_pay_open_status` tinyint(1) DEFAULT '0' COMMENT '当前节点是否打开了支付',
  `revoke_status` tinyint(1) DEFAULT '0' COMMENT '当前节点是否允许回退',
  `data_import_status` tinyint(1) DEFAULT '0' COMMENT '是否开启了数据导入',
  `being_submit_check` tinyint(1) DEFAULT '0',
  `audit_user_type` int NOT NULL DEFAULT '1' COMMENT '节点处理人类型, 1:一般负责人, 2:逐级审批负责人',
  PRIMARY KEY (`audit_node_id`),
  KEY `idx_next_id` (`next_id`),
  KEY `idx_prev_id` (`prev_id`)
) ENGINE=InnoDB AUTO_INCREMENT=54902 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;